import { test, expect } from '@playwright/test';
import { TestPage } from '../pages/TestPage';

/**
 * TestPageTest Test Suite
 * Generated by claude-playwright scaffold
 */
test.describe('TestPageTest', () => {
  let testpage: TestPage;

  test.beforeEach(async ({ page }) => {
    testpage = new TestPage(page);
    await testpage.goto();
  });

  test('should load page successfully', async ({ page }) => {
    await testpage.waitForLoad();
    await expect(page).toHaveTitle(/.+/);
    await expect(testpage.isLoaded()).resolves.toBeTruthy();
  });

  test('should display main content', async ({ page }) => {
    await testpage.waitForLoad();
    // Add your content assertions here
  });
});
